import type { Metadata } from "next";
import Style from "./profile.module.css";
import ProfileDetails from "./profiledetails/ProfileDetails";
import { Poppins } from "next/font/google";
import AllLinks from "./profileAll_Links/AllLinks";
import Profile_Rate from "./profile_compeleting_rate/Profile_Rate";
const poppins = Poppins({
  weight: ["200", "200"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Profile",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <main
      className={`${Style.Main} ${poppins.className} md:text-xs lg:text-base  pr-10 pl-10 max-sm:pr-5 max-sm:pl-5  pt-20`}
    >
      <div className=" text-white mt-5">
        <Profile_Rate />
      </div>

      <div className=" flex flex-col md:flex-row md:gap-10 h-full ">
        {/* left_part_start */}
        <div className=" profileLeftDiv pr-5 pl-5 backdrop:filter backdrop-blur-3xl rounded-md  text-white w-full  md:w-3/5 lg:w-2/5 pb-5">
          {/* profile_Image_part_start */}
          <div className=" flex items-center justify-center mt-5">
              <ProfileDetails />
          </div>
          {/* profile_Image_part_end */}
          {/* divider_start */}
          <div className=" w-full border-t border-dashed border-cyan-700 mt-5 mb-5"></div>
          {/* divider_end */}
          <AllLinks />
        </div>
        {/* left_part_end */}

        <div className=" w-full  pr-5 pl-5 backdrop:filter backdrop-blur-3xl rounded-md pt-5 ">
          {children}
        </div>
      </div>
    </main>
  );
}
